name: Build and deploy

on:
  push:
    branches:
      - 'master'
  pull_request: {}
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 5 #pulling dependencies potentially twice - host OS and docker layer
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache for NodeJS dependencies - Docker layer
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: node-modules-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: make cv
      - uses: satackey/action-docker-layer-caching@v0.0.8
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
      - run: yarn deploy