name: Build CV

on:
  push:
    branches:
      - main
    paths:
      - 'src/cv/cv.tex'
      - '.github/workflows/cv.yml'

jobs:
  build-cv:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build CV
        working-directory: src/cv
        run: docker run --rm -v $(pwd):/data -v $(pwd)/../images:/images vipintm/xelatex make
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.CV_PULL_REQUEST_PAT }}
          title: Updated CV
          body: Changes to cv.tex resulted in a change of cv.pdf
