name: Build CV

on:
  push:
    branches:
      - "master"
    paths:
      - 'src/cv/cv.tex'
      - '.github/workflows/cv.yml'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build CV
        working-directory: src/cv
        run: docker run --rm -v $(shell pwd):/data vipintm/xelatex make
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        token: {{ secrets.CV_PULL_REQUEST_PAT }}