# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build CV

on:
  push:
    branches:
      - main
    paths:
      - 'cv/cv.tex'
      - '.github/workflows/cv.yml'

jobs:
  build-cv:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build CV
        run: make cv
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.CV_PULL_REQUEST_PAT }}
          title: Updated CV
          body: Changes to cv.tex resulted in a change of cv.pdf
